### PR TITLE
Update readme and add installation instruction

### PR DESCRIPTION
**Pull request by albertskog**
Hi, thanks for the plugin! I made some updates to the readmes in case you are interested!

### CODE REVIEW

**Comment by duGuillaume** [comment]
Mhh 1.6 branch shouldn't use material, i'll fix this evening, i keep you in touch

Thx for your pull requests

**Comment by duGuillaume** [comment]
into account template we are using font-awesome, but where do you see material ?
Thx

**Comment by albertskog** [comment]
Oops, do you mean this line?

`This module uses Material Icon.`

I think I did too much copy-paste.. Have removed it now!

**Comment by mhd6** [comment]
Hello, great work thank you for sharing, Ya til a new version for the 1.6.1.20 ?

**Comment by duGuillaume** [comment]
this should be compatible, if not please open new issue.

**Pull request merged**
